apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubemind-api.fullname" . }}
  labels:
    {{- include "kubemind-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | default "" | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 32) | quote }}
  alert-slack-webhook: {{ .Values.secrets.alertSlackWebhook | default "" | quote }}
  alert-discord-webhook: {{ .Values.secrets.alertDiscordWebhook | default "" | quote }}
  alert-email-smtp-host: {{ .Values.secrets.alertEmailSmtpHost | default "" | quote }}
  alert-email-smtp-port: {{ .Values.secrets.alertEmailSmtpPort | default "587" | quote }}
  alert-email-from: {{ .Values.secrets.alertEmailFrom | default "" | quote }}
  alert-email-password: {{ .Values.secrets.alertEmailPassword | default "" | quote }}
  alert-email-to: {{ .Values.secrets.alertEmailTo | default "" | quote }}
  alert-webhook-url: {{ .Values.secrets.alertWebhookUrl | default "" | quote }}
