apiVersion: v1
kind: Secret
metadata:
  name: {{ include "KubeMind.fullname" . }}-secrets
  labels:
    {{- include "KubeMind.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ index .Values "kubemind-api" "secrets" "databaseUrl" | default "" | quote }}
  jwt-secret: {{ index .Values "kubemind-api" "secrets" "jwtSecret" | default (randAlphaNum 32) | quote }}
