apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubemind-agent.fullname" . }}
  labels:
    {{- include "kubemind-agent.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "kubemind-agent.selectorLabels" . | nindent 6 }}
